#ifndef STYLES_READER_H
#define STYLES_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct MyGame_Sample_Property_table *MyGame_Sample_Property_table_t;
typedef struct MyGame_Sample_Property_table *MyGame_Sample_Property_mutable_table_t;
typedef const flatbuffers_uoffset_t *MyGame_Sample_Property_vec_t;
typedef flatbuffers_uoffset_t *MyGame_Sample_Property_mutable_vec_t;
typedef const struct MyGame_Sample_StaticRule_table *MyGame_Sample_StaticRule_table_t;
typedef struct MyGame_Sample_StaticRule_table *MyGame_Sample_StaticRule_mutable_table_t;
typedef const flatbuffers_uoffset_t *MyGame_Sample_StaticRule_vec_t;
typedef flatbuffers_uoffset_t *MyGame_Sample_StaticRule_mutable_vec_t;
typedef const struct MyGame_Sample_DynamicProperty_table *MyGame_Sample_DynamicProperty_table_t;
typedef struct MyGame_Sample_DynamicProperty_table *MyGame_Sample_DynamicProperty_mutable_table_t;
typedef const flatbuffers_uoffset_t *MyGame_Sample_DynamicProperty_vec_t;
typedef flatbuffers_uoffset_t *MyGame_Sample_DynamicProperty_mutable_vec_t;
typedef const struct MyGame_Sample_DynamicRule_table *MyGame_Sample_DynamicRule_table_t;
typedef struct MyGame_Sample_DynamicRule_table *MyGame_Sample_DynamicRule_mutable_table_t;
typedef const flatbuffers_uoffset_t *MyGame_Sample_DynamicRule_vec_t;
typedef flatbuffers_uoffset_t *MyGame_Sample_DynamicRule_mutable_vec_t;
typedef const struct MyGame_Sample_Styles_table *MyGame_Sample_Styles_table_t;
typedef struct MyGame_Sample_Styles_table *MyGame_Sample_Styles_mutable_table_t;
typedef const flatbuffers_uoffset_t *MyGame_Sample_Styles_vec_t;
typedef flatbuffers_uoffset_t *MyGame_Sample_Styles_mutable_vec_t;
#ifndef MyGame_Sample_Property_file_identifier
#define MyGame_Sample_Property_file_identifier 0
#endif
/* deprecated, use MyGame_Sample_Property_file_identifier */
#ifndef MyGame_Sample_Property_identifier
#define MyGame_Sample_Property_identifier 0
#endif
#define MyGame_Sample_Property_type_hash ((flatbuffers_thash_t)0x7e468e6a)
#define MyGame_Sample_Property_type_identifier "\x6a\x8e\x46\x7e"
#ifndef MyGame_Sample_Property_file_extension
#define MyGame_Sample_Property_file_extension "bin"
#endif
#ifndef MyGame_Sample_StaticRule_file_identifier
#define MyGame_Sample_StaticRule_file_identifier 0
#endif
/* deprecated, use MyGame_Sample_StaticRule_file_identifier */
#ifndef MyGame_Sample_StaticRule_identifier
#define MyGame_Sample_StaticRule_identifier 0
#endif
#define MyGame_Sample_StaticRule_type_hash ((flatbuffers_thash_t)0x35db762f)
#define MyGame_Sample_StaticRule_type_identifier "\x2f\x76\xdb\x35"
#ifndef MyGame_Sample_StaticRule_file_extension
#define MyGame_Sample_StaticRule_file_extension "bin"
#endif
#ifndef MyGame_Sample_DynamicProperty_file_identifier
#define MyGame_Sample_DynamicProperty_file_identifier 0
#endif
/* deprecated, use MyGame_Sample_DynamicProperty_file_identifier */
#ifndef MyGame_Sample_DynamicProperty_identifier
#define MyGame_Sample_DynamicProperty_identifier 0
#endif
#define MyGame_Sample_DynamicProperty_type_hash ((flatbuffers_thash_t)0x39faaeb1)
#define MyGame_Sample_DynamicProperty_type_identifier "\xb1\xae\xfa\x39"
#ifndef MyGame_Sample_DynamicProperty_file_extension
#define MyGame_Sample_DynamicProperty_file_extension "bin"
#endif
#ifndef MyGame_Sample_DynamicRule_file_identifier
#define MyGame_Sample_DynamicRule_file_identifier 0
#endif
/* deprecated, use MyGame_Sample_DynamicRule_file_identifier */
#ifndef MyGame_Sample_DynamicRule_identifier
#define MyGame_Sample_DynamicRule_identifier 0
#endif
#define MyGame_Sample_DynamicRule_type_hash ((flatbuffers_thash_t)0x5b42def6)
#define MyGame_Sample_DynamicRule_type_identifier "\xf6\xde\x42\x5b"
#ifndef MyGame_Sample_DynamicRule_file_extension
#define MyGame_Sample_DynamicRule_file_extension "bin"
#endif
#ifndef MyGame_Sample_Styles_file_identifier
#define MyGame_Sample_Styles_file_identifier 0
#endif
/* deprecated, use MyGame_Sample_Styles_file_identifier */
#ifndef MyGame_Sample_Styles_identifier
#define MyGame_Sample_Styles_identifier 0
#endif
#define MyGame_Sample_Styles_type_hash ((flatbuffers_thash_t)0x8174aa5)
#define MyGame_Sample_Styles_type_identifier "\xa5\x4a\x17\x08"
#ifndef MyGame_Sample_Styles_file_extension
#define MyGame_Sample_Styles_file_extension "bin"
#endif



struct MyGame_Sample_Property_table { uint8_t unused__; };

static inline size_t MyGame_Sample_Property_vec_len(MyGame_Sample_Property_vec_t vec)
__flatbuffers_vec_len(vec)
static inline MyGame_Sample_Property_table_t MyGame_Sample_Property_vec_at(MyGame_Sample_Property_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(MyGame_Sample_Property_table_t, vec, i, 0)
__flatbuffers_table_as_root(MyGame_Sample_Property)

__flatbuffers_define_string_field(0, MyGame_Sample_Property, key, 0)
__flatbuffers_define_string_field(1, MyGame_Sample_Property, value, 0)

struct MyGame_Sample_StaticRule_table { uint8_t unused__; };

static inline size_t MyGame_Sample_StaticRule_vec_len(MyGame_Sample_StaticRule_vec_t vec)
__flatbuffers_vec_len(vec)
static inline MyGame_Sample_StaticRule_table_t MyGame_Sample_StaticRule_vec_at(MyGame_Sample_StaticRule_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(MyGame_Sample_StaticRule_table_t, vec, i, 0)
__flatbuffers_table_as_root(MyGame_Sample_StaticRule)

__flatbuffers_define_string_field(0, MyGame_Sample_StaticRule, name, 0)
__flatbuffers_define_vector_field(1, MyGame_Sample_StaticRule, properties, MyGame_Sample_Property_vec_t, 0)

struct MyGame_Sample_DynamicProperty_table { uint8_t unused__; };

static inline size_t MyGame_Sample_DynamicProperty_vec_len(MyGame_Sample_DynamicProperty_vec_t vec)
__flatbuffers_vec_len(vec)
static inline MyGame_Sample_DynamicProperty_table_t MyGame_Sample_DynamicProperty_vec_at(MyGame_Sample_DynamicProperty_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(MyGame_Sample_DynamicProperty_table_t, vec, i, 0)
__flatbuffers_table_as_root(MyGame_Sample_DynamicProperty)

__flatbuffers_define_string_field(0, MyGame_Sample_DynamicProperty, name, 0)
__flatbuffers_define_vector_field(1, MyGame_Sample_DynamicProperty, properties, MyGame_Sample_Property_vec_t, 0)

struct MyGame_Sample_DynamicRule_table { uint8_t unused__; };

static inline size_t MyGame_Sample_DynamicRule_vec_len(MyGame_Sample_DynamicRule_vec_t vec)
__flatbuffers_vec_len(vec)
static inline MyGame_Sample_DynamicRule_table_t MyGame_Sample_DynamicRule_vec_at(MyGame_Sample_DynamicRule_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(MyGame_Sample_DynamicRule_table_t, vec, i, 0)
__flatbuffers_table_as_root(MyGame_Sample_DynamicRule)

__flatbuffers_define_string_field(0, MyGame_Sample_DynamicRule, prefix, 0)
__flatbuffers_define_vector_field(1, MyGame_Sample_DynamicRule, values, flatbuffers_string_vec_t, 0)
__flatbuffers_define_vector_field(2, MyGame_Sample_DynamicRule, properties, MyGame_Sample_DynamicProperty_vec_t, 0)

struct MyGame_Sample_Styles_table { uint8_t unused__; };

static inline size_t MyGame_Sample_Styles_vec_len(MyGame_Sample_Styles_vec_t vec)
__flatbuffers_vec_len(vec)
static inline MyGame_Sample_Styles_table_t MyGame_Sample_Styles_vec_at(MyGame_Sample_Styles_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(MyGame_Sample_Styles_table_t, vec, i, 0)
__flatbuffers_table_as_root(MyGame_Sample_Styles)

__flatbuffers_define_vector_field(0, MyGame_Sample_Styles, static_rules, MyGame_Sample_StaticRule_vec_t, 0)
__flatbuffers_define_vector_field(1, MyGame_Sample_Styles, dynamic_rules, MyGame_Sample_DynamicRule_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* STYLES_READER_H */
