[static_rules.flex]
display = "flex"

[static_rules.body]
background-color = "#0f172a"
color = "#f8fafc"

[static_rules.button]
background-color = "#3b82f6"
color = "white"
padding = "10px 20px"
border-radius = "5px"
